export default {
  SET_SELECTED_CAT_ID: "SET_SELECTED_CAT_ID",
  SET_CURRENT_CAT: "SET_CURRENT_CAT",
  SET_EVENTS: "SET_EVENTS",
  UPDATE_CAT_ATTRIBUTES: "UPDATE_CAT_ATTRIBUTES",
  SET_SCENE: "SET_SCENE",
} as const;
